### ISSUE TITLE
Miscellaneous bugs and feature requests

### ISSUE THREAD

**Issue by MarioPossamato** [BrickBench/BrickBench#28]
Bugs:
- Loading a mesh from ***Meshes*** list inside the ***Meshes*** tab, then going back to the ***Scene*** tab resets the view to the origin and disables shadows.

Features:
- Implement support for exporting individual meshes in the ***Meshes*** list inside the ***Meshes*** tab as other model formats, such as *.gltf, *.fbx, *.obj, *.dae, etc.;
- Implement support for exporting entire levels (or individual areas) as other model formats, such as *.gltf, *.fbx, *.obj, *.dae, etc.;
- Implement support for viewing character files, as well as their animations (if possible);
- Implement more accurate rendering for ***LEGO® Batman™: The Videogame*** levels;
- Implement a level opening system that, in the ***File*** menu, there would be two new buttons,
	***Select Map Folder***, and ***Maps***.  The "Maps" button will be disabled until the map folder
	is selected.  Once it is selected, however, the ***Maps*** button will be enabled, and will have different
	categories, each with their own subcategories.  For example, in ***LEGO® Batman™: The Videogame*** it would be the following:
```
┌──────┐
│ File │
├──────┴────────────────────┐
│ Load Project              │
│ Load Map From File/Folder │
│ Select Map Folder         ├───────────┬─────────────────────────┬─────────────────────────┐
│ Maps                    > │ Hero    > │ The Riddler's Revenge > │ You Can Bank On Batman  │
│ Open Recent             > │ Villain > │ Power Crazed Penguin  > │ An Icy Reception        │
├───────────────────────────┼───────────┤ The Joker's Return    > │ Two-Face Chase          │
│ Save Project              │           └─────────────────────────┤ A Poisonous Appointment │
│ Export Map                │                                     │ The Face-Off            │
│ Create Patches            │                                     └─────────────────────────┘
├───────────────────────────┤
│ Import THINGS_PC.GSC      │
├───────────────────────────┤
│ Settings                  │
│ Quit                      │
└───────────────────────────┘
```
So that the following could be selected:
```
File
└───Maps
    └───Hero
        └───The Riddler's Revenge
            └───You Can Bank On Batman
```
Selecting one of the level names, for example ***You Can Bank On Batman***, will load all the areas inside
*"LEVELS\HERO\CHAPTER1\GOTHAMSTREETS\"*.  I don't know how other Traveler's Tales LEGO games have their
levels set up, since I don't own any others aside from LB1, but I think that would be a very convenient addition.

**Comment by javster101** [comment]
The mesh bug is fixed in the next BrickBench version. We can't give a timeline for its release yet though.

As for exporting levels, we are currently working on that and other related features. The main complication is related to material properties, as the material definitions in the TT engine do not really match any existing format, so exporting the materials for the meshes will be a challenge. Exporting the meshes themselves, however, should be simple enough.

Character files are not really an end goal of BrickBench. There is some work on that being done with other people, but we likely will not add support for character editing.

I like the idea with whole-map viewing. Likely that would take the form of a generalized concept of a "mod" which simplifies the editing of multiple map files for a single game, including file management and simplified exporting. We will likely begin work on that after this release.

**Comment by javster101** [comment]
#20 is the current work being done related to whole-game viewing, we can extend it to the entire game instead of just on a per-level basis

**Comment by MarioPossamato** [comment]
Ah, ok, sweet! :)  Also, in the ***Meshes*** and ***Materials*** lists inside the ***Meshes*** tab, I have to click each individual item in order to update the visuals.  Would it be possible to implement the use of arrow keys for that (if it hasn't been implemented already)?

**Comment by javster101** [comment]
Sure, we'll work on that

**Comment by MarioPossamato** [comment]
Thanks! :)
